fix: fix tuistignore when local path are specified
tuist/tuist pull request #3456
Opened 2021-09-16 08:13 UTC by danyf90

### Short description 📝

relative path (as the one we are specifying in Tuist own .tuistignore) were not matched correctly

### Checklist ✅

- [ ] The code architecture and patterns are consistent with the rest of the codebase.
- [ ] The changes have been tested following the [documented guidelines](https://docs.tuist.io/contributors/testing-strategy/).
- [ ] The `CHANGELOG.md` has been updated to reflect the changes. In case of a breaking change, it's been flagged as such.
- [ ] In case the PR introduces changes that affect users, the documentation has been updated.

2021-09-19 12:34 UTC, adellibovi requested changes
Since this is a more internal feature and we do not have expectations on the syntax of `.tuistignore`, I would rather change the content of the existing .tuistignore to be `projects/tuist/fixtures/**` instead of `projects/tuist/fixtures` rather than adding more logic. What do you think?

2021-09-19 16:44 UTC, danyf90 commented
Not sure, I agree it's internal, but this might change in the future.
I would prefer to keep a syntax similar to the `.gitignore` to be as less surprising as possible.

2021-09-20 17:07 UTC, adellibovi commented
I think if we start adding more behaviour/functionalities we may go into the direction where users would expect this to behave like `.gitignore` which actually have a lot more of features (like negating logic etc..). Functionality can always be added later, but removing it is harder.
Said so, I would still personally prefer to adapt our `.tuistignore` instead of extending the functionality, anyway I will approve the PR 😃 
It would be good to hear other opinions cc @fortmarek @pepibumur

2021-09-20 17:07 UTC, adellibovi approved these changes

2021-09-20 19:32 UTC, danyf90 commented
@adellibovi I agree with your points, but in this case adding a folder would have no effect as the tuistignore works only on files, so it would be weird to have an entry which actually does nothing

2021-09-22 14:45 UTC, pepibumur approved these changes

2021-09-22 14:45 UTC, pepibumur commented
CHANGELOG entry is missing but I'll update it in `main` to avoid delaying the merge further.

2021-09-22 14:45 UTC, merged