Persist Package.swift file along with resolved file
tuist/tuist pull request #3661
Opened 2021-11-12 22:01 UTC by thedavidharris

### Short description 📝

This also persists the generated Package.swift file alongside the Package.resolved; for various bits of open source tooling, both files are required.

### Checklist ✅

- [ ✅] The code architecture and patterns are consistent with the rest of the codebase.
- [ ✅] The changes have been tested following the [documented guidelines](https://docs.tuist.io/contributors/testing-strategy/).
- [ ] The `CHANGELOG.md` has been updated to reflect the changes. In case of a breaking change, it's been flagged as such.
- [ ✅] In case the PR introduces changes that affect users, the documentation has been updated.
- [ ✅] In case the PR introduces changes that affect how the cache artifact is generated starting from the `TuistGraph.Target`, the `Constants.cacheVersion` has been updated.

2021-11-14 09:44 UTC, fortmarek reviewed
Great addition @thedavidharris! I think we should also put this in the documentation somewhere.

2021-11-14 09:44 UTC, fortmarek commented on Sources/TuistDependencies/SwiftPackageManager/SwiftPackageManagerInteractor.swift
> +            .appending(component: Constants.DependenciesDirectory.lockfilesDirectoryName)
I'd put this in the `SwiftPackageManager` folder as suggested by @danyf90

2021-11-15 17:00 UTC, danyf90 requested changes
If we persist the Package.swift we should persist the Carthage as well

2021-11-15 18:34 UTC, thedavidharris commented
> If we persist the `Package.swift` we should persist the `Cartfile` as well

Good call, added similar logic/tests for Carthage.

2021-11-15 18:44 UTC, danyf90 approved these changes

2021-11-16 08:30 UTC, fortmarek approved these changes

2021-11-16 15:43 UTC, merged