Removed Swift tests config from CI pipeline
tuist/tuist pull request #4063
Opened 2022-01-26 19:28 UTC by mohitsaxenaknoldus

Resolves https://github.com/tuist/tuist/issues/YYY
Request for comments document (if applies):

### Short description 📝

Closes #4046 
> Describe here the purpose of your PR.

### How to test the changes locally 🧐

> Include a set of steps for the reviewer to test the changes locally.

### Checklist ✅

- [x] The code architecture and patterns are consistent with the rest of the codebase.
- [x] The changes have been tested following the [documented guidelines](https://docs.tuist.io/contributors/testing-strategy/).
- [ ] The `CHANGELOG.md` has been updated to reflect the changes. In case of a breaking change, it's been flagged as such.
- [x] In case the PR introduces changes that affect users, the documentation has been updated.
- [ ] In case the PR introduces changes that affect how the cache artifact is generated starting from the `TuistGraph.Target`, the `Constants.cacheVersion` has been updated.

2022-01-26 19:48 UTC, danyf90 approved these changes

2022-01-26 20:02 UTC, ezraberch commented on projects/fourier/test/fourier/services/test/tuist/unit_test.rb
> -              .with("swift", "test")
This is the internal unit test for fourier. What this does is verify that when you call `fourier test tuist unit`, fourier will call `tuist dependencies fetch`, `tuist test`, and `swift test`. Removing these 3 lines will make the unit test no longer expect `swift test` to be called, but won't actually change the fact that it is called. Thus the test will now fail.

2022-01-26 20:05 UTC, danyf90 requested changes
The file to be changed is `projects/fourier/lib/fourier/services/test/tuist`

2022-01-26 20:27 UTC, danyf90 requested changes
Could you also rebase on master? 🙏

2022-01-26 20:27 UTC, danyf90 commented on projects/fourier/lib/fourier/services/test/tuist/unit.rb
>              end
should be removed as well

2022-01-26 20:27 UTC, danyf90 commented on projects/fourier/test/fourier/services/test/tuist/unit_test.rb
> +
you should remove this as well.
Aslo, pay attention to not leaving empty spaces in empty line or linting will fail

2022-01-26 20:34 UTC, mohitsaxenaknoldus commented
> Could you also rebase on master? pray

I don't see a master branch.

2022-01-26 20:36 UTC, ezraberch commented
> I don't see a master branch.

`main` is the master branch.

2022-01-26 20:46 UTC, mohitsaxenaknoldus commented
> > I don't see a master branch.
> 
> `main` is the master branch.

Up to date.

2022-01-26 20:54 UTC, danyf90 commented on projects/fourier/lib/fourier/services/test/tuist/unit.rb
>              end
This doesn't seem done. I refer to the `end` of the `if`

2022-01-26 20:54 UTC, danyf90 commented
https://github.com/tuist/tuist/pull/4063#discussion_r793039468 🙏

2022-01-26 21:17 UTC, danyf90 commented on projects/fourier/test/fourier/services/test/tuist/unit_test.rb
>              # When/Then
```suggestion

            # When/Then
```

2022-01-27 07:51 UTC, danyf90 approved these changes

2022-01-27 08:34 UTC, adellibovi approved these changes

2022-01-27 08:34 UTC, merged

2022-01-27 12:58 UTC, luispadron commented
@allcontributors add @mohitsaxenaknoldus for code