Fix `tuist generate` performance when no parameter is passed
tuist/tuist pull request #4080
Opened 2022-01-28 14:48 UTC by adellibovi

### Short description 📝

Currently (in 3.0), we were loading the target names by loading each manifest synchronously, this revert the change and loads the total list of target from the graph.

### How to test the changes locally 🧐

> Include a set of steps for the reviewer to test the changes locally.

### Checklist ✅

- [ ] The code architecture and patterns are consistent with the rest of the codebase.
- [ ] The changes have been tested following the [documented guidelines](https://docs.tuist.io/contributors/testing-strategy/).
- [ ] The `CHANGELOG.md` has been updated to reflect the changes. In case of a breaking change, it's been flagged as such.
- [ ] In case the PR introduces changes that affect users, the documentation has been updated.
- [ ] In case the PR introduces changes that affect how the cache artifact is generated starting from the `TuistGraph.Target`, the `Constants.cacheVersion` has been updated.

2022-01-28 16:20 UTC, danyf90 requested changes

2022-01-30 09:02 UTC, adellibovi commented on Sources/TuistKit/Services/GenerateService.swift
> +            sources: sources.isEmpty ? nil : sources,
Now it uses `allInternalTargets`, if I understood correctly should be the same behaviour without the performance hit :)

2022-01-30 09:44 UTC, danyf90 requested changes

2022-01-30 09:44 UTC, danyf90 commented on Sources/TuistCore/Graph/GraphTraverser.swift
> +
Maybe you can simplify this by implementing it as a filter on the `allTargets` method?

2022-01-30 09:44 UTC, danyf90 commented on Sources/TuistCore/Graph/GraphTraverser.swift
> +
Maybe it could even be an extension in the `GraphTraversing.swift` so it would apply to all implementations 🤔

2022-01-30 09:44 UTC, danyf90 commented on Sources/TuistKit/Services/GenerateService.swift
> +            sources: sources.isEmpty ? nil : sources,
Nice! can you do the same also for the `CacheWarmService`

2022-01-30 09:44 UTC, danyf90 commented on Sources/TuistKit/Generator/GeneratorFactory.swift
> +               sources: Set<String>?,
Could you remember me when it can be empty? If never, we can use the empty set instead of `nil` to request to focus on internal targets

2022-01-30 19:10 UTC, danyf90 approved these changes

2022-01-30 21:14 UTC, merged