Use a custom sort and trim function when merging settings
tuist/tuist pull request #4325
Opened 2022-03-31 12:43 UTC by a-sarris

Resolves https://github.com/tuist/tuist/issues/4315
Request for comments document (if applies):

### Short description 📝

Fix merging of settings when settings require duplicate flags with preserved order.

I have limited experience with the codebase, this is something to get the conversation started and maybe find an even better solution.

### How to test the changes locally 🧐

Issue Resolves https://github.com/tuist/tuist/issues/4315 has a unit test that describes the issue

### Checklist ✅

- [ ] The code architecture and patterns are consistent with the rest of the codebase.
- [ ] The changes have been tested following the [documented guidelines](https://docs.tuist.io/contributors/testing-strategy/).
- [ ] The PR includes the label `changelog:added`, `changelog:fixed`, or `changelog:changed`, whenever it should be included in the “Added”, “Fixed” or “Changed” section of the CHANGELOG. Note: when included in the CHANGELOG, the title of the PR will be used as entry, please make sure it is clear and suitable.
- [ ] In case the PR introduces changes that affect users, the documentation has been updated.
- [ ] In case the PR introduces changes that affect how the cache artifact is generated starting from the `TuistGraph.Target`, the `Constants.cacheVersion` has been updated.

2022-03-31 13:30 UTC, danyf90 requested changes

2022-03-31 13:30 UTC, danyf90 commented on Sources/TuistGenerator/Extensions/Array+Extras.swift
> +    func sortAndTrim(element: String) -> [String] {
I would define it in `Sources/TuistGenerator/Utils/SettingsHelper.swift`

2022-03-31 13:30 UTC, danyf90 commented on Sources/TuistGenerator/Extensions/Array+Extras.swift
> +        }.enumerated().compactMap { (index, item) in
```suggestion
        return self
            .sorted { first, _ in first.contains(element) }
            .enumerated()
            .compactMap { (index, item) in
```

2022-03-31 16:15 UTC, danyf90 approved these changes

2022-03-31 16:15 UTC, danyf90 commented on Sources/TuistGenerator/Utils/SettingsHelper.swift
> +    private func sortAndTrim(array: [String], element: String) -> [String] {
nit: can be static

2022-03-31 18:15 UTC, kwridan commented
Mind running ` ./fourier lint tuist --fix` to run the formatter to address the lint warnings? 

Thanks again!

2022-03-31 18:16 UTC, kwridan commented
@all-contributors add @a-sarris for code

2022-04-01 15:24 UTC, a-sarris commented on Sources/TuistGenerator/Utils/SettingsHelper.swift
> +    private func sortAndTrim(array: [String], element: String) -> [String] {
fixed

2022-04-01 17:51 UTC, merged