Fix: lproj directories not being detected as resources
tuist/tuist pull request #4507
Opened 2022-05-30 08:49 UTC by ffittschen

Resolves #4505
Request for comments document (if applies): -

### Short description 📝

Adds the `lproj` extension to the [`validFolderExtensions`](https://github.com/tuist/tuist/blob/6001d23278f345233f9395862b5aedaa12bd33d3/Sources/TuistGraph/Models/Target.swift#L13) so that the [`isResource(path:)`](https://github.com/tuist/tuist/blob/8dd9ae027f4c56ed6820762605d41d916e31e3d8/Sources/TuistCore/Graph/ModelExtensions/Target%2BCore.swift#L35) will return `true` instead of `false` when it's input is a `lproj` directory.

Question for the maintainers: Is the addition in the tests enough, or should I also add some `lproj` to any fixtures to assert that a `...Resources` target is being generated?

### How to test the changes locally 🧐

1. Use the sample project attached to #4505
2. Run `tuist fetch && tuist generate`
3. Open the `AppCenter` project in `Tuist > Dependencies > SwiftPackageManager > .build > checkouts`
4. See that Tuist generated the `AppCenterDistributeResources` target

### Checklist ✅

- [x] The code architecture and patterns are consistent with the rest of the codebase.
- [ ] The changes have been tested following the [documented guidelines](https://docs.tuist.io/contributors/testing-strategy/).
- [ ] The PR includes the label `changelog:added`, `changelog:fixed`, or `changelog:changed`, whenever it should be included in the “Added”, “Fixed” or “Changed” section of the CHANGELOG. Note: when included in the CHANGELOG, the title of the PR will be used as entry, please make sure it is clear and suitable.
- [ ] In case the PR introduces changes that affect users, the documentation has been updated.
- [ ] In case the PR introduces changes that affect how the cache artifact is generated starting from the `TuistGraph.Target`, the `Constants.cacheVersion` has been updated.

2022-05-30 08:53 UTC, danyf90 requested changes
I'm not sure it's the right fix, because AFAIK adding `lproj` folder as resources works fine in general, and the issue is only when they are added as automatic resources from SPM, so there might be something different in that path to be investigated

2022-05-30 10:47 UTC, ffittschen commented
Fair enough. I'll try to find out if we could mimic the workaround explained in https://github.com/tuist/tuist/issues/4435#issuecomment-1137393368, i.e. assuming the Package.swift file has `resources: [.process("Resources"]` if it in fact does not, but a `Resources` directory exists.

2022-05-30 11:52 UTC, danyf90 commented
> Fair enough. I'll try to find out if we could mimic the workaround explained in [#4435 (comment)](https://github.com/tuist/tuist/issues/4435#issuecomment-1137393368), i.e. assuming the Package.swift file has `resources: [.process("Resources"]` if it in fact does not, but a `Resources` directory exists.

the logic is already there, but it looks like the lproj are handled by a different logic WRT other resources, and that logic is missing somehow for targets coming from Dependencies.swift

2022-06-06 20:18 UTC, danyf90 commented
This should be the required fix: https://github.com/tuist/tuist/pull/4532

2022-06-06 20:18 UTC, closed without merging