Update AssetsTemplate to support SwiftUI
tuist/tuist pull request #4838
Opened 2022-10-23 02:47 UTC by kyungpyoda

Resolves https://github.com/tuist/tuist/issues/3595

### Short description 📝

Update AssetsTemplate to support SwiftUI

2022-10-23 09:06 UTC, danyf90 requested changes

2022-10-23 14:41 UTC, luispadron approved these changes

2022-10-23 15:42 UTC, kyungpyoda commented on CHANGELOG.md
> +- Update AssetsTemplate to support SwiftUI [#4838](https://github.com/tuist/tuist/pull/4838) by [kyungpyoda](https://github.com/kyungpyoda).
I've deleted that commit. Thx :)

2022-10-23 15:47 UTC, danyf90 approved these changes

2022-10-23 19:35 UTC, fortmarek approved these changes

2022-10-29 03:57 UTC, kyungpyoda commented
I really don't know what is wrong 🤔

2022-10-31 08:41 UTC, danyf90 commented
@kyungpyoda have you tried to check what is failing? keeping to merge main won't fix the issue :D

2022-10-31 08:41 UTC, danyf90 commented
@allcontributors add @kyungpyoda for code

2022-11-05 02:23 UTC, kyungpyoda commented
@danyf90  I forgot a `#endif`... 😓 now I fixed it.

2022-11-05 16:23 UTC, merged