Update Tuist to build with Xcode 14.1
tuist/tuist pull request #5029
Opened 2023-02-06 17:02 UTC by thedavidharris

### Short description 📝

Moves Tuist to compile on CI and build with Xcode 14.1. This unblocks a PR related to multi-platform build targets and better aligns with current development versions.

### How to test the changes locally 🧐

### Contributor checklist ✅

- [ ] The code has been linted using run `./fourier lint tuist --fix`
- [ ] The change is tested via unit testing or acceptance testing, or both
- [ ] The title of the PR is formulated in a way that is usable as a changelog entry
- [ ] In case the PR introduces changes that affect users, the documentation has been updated

### Reviewer checklist ✅

- [ ] The code architecture and patterns are consistent with the rest of the codebase
- [ ] Contributors have checked that, if needed, the PR includes the label `changelog:added`, `changelog:fixed`, or `changelog:changed`, and the title is usable as a changelog entry

2023-02-06 17:13 UTC, thedavidharris commented on Sources/ProjectDescription/Config.swift
> +///     compatibleXcodeVersions: ["14.3"],
Just to trigger CI

2023-02-06 18:54 UTC, danyf90 requested changes
I think you also need to update the CI jobs to use the new images or Xcode builds, isn't it?

2023-02-06 18:54 UTC, danyf90 commented on .xcode-version-libraries
> +14.1
I think this should remain the old one to not impact the users.

2023-02-07 08:22 UTC, kwridan commented
heads up there's a high chance we'll run into this issue https://github.com/apple/swift-package-manager/issues/5767 😞

2023-02-14 23:00 UTC, thedavidharris commented
I'm not going to get a chance to follow this up in the short-term, so closing this for someone else to pick up.

https://github.com/tuist/tuist/pull/5005 depends on a similar change.

2023-02-15 05:36 UTC, danyf90 commented
I'll try to fix this 🤞

2023-02-16 08:14 UTC, danyf90 approved these changes

2023-05-25 12:34 UTC, closed without merging