Allow to add carthage options on Dependencies.swift
tuist/tuist pull request #5110
Opened 2023-03-18 09:51 UTC by didix21

Resolves https://github.com/tuist/tuist/issues/3586

### Short description 📝

Allow to add Carthage options on Dependencies.swift

The available options are:

- Don't use downloaded binaries when possible: `--no-use-binaries`.
- Use authentication credentials from ~/.netrc file when downloading binary only frameworks: `--use-netrc`.
- Use cached builds when possible: `--cache-builds`.
- Use the new resolver codeline when calculating dependencies: `--new-resolver`.
- Resolves #3586

### How to test the changes locally 🧐

> Include a set of steps for the reviewer to test the changes locally (see [the documentation](https://docs.tuist.io/contributors/testing-strategy) for reference).

### Contributor checklist ✅

- [x] The code has been linted using run `./fourier lint tuist --fix`
- [x] The change is tested via unit testing or acceptance testing, or both
- [x] The title of the PR is formulated in a way that is usable as a changelog entry
- [x] In case the PR introduces changes that affect users, the documentation has been updated

### Reviewer checklist ✅

- [ ] The code architecture and patterns are consistent with the rest of the codebase
- [ ] Reviewer has checked that, if needed, the PR includes the label `changelog:added`, `changelog:fixed`, or `changelog:changed`, and the title is usable as a changelog entry

2023-03-18 14:06 UTC, danyf90 requested changes
Can you update the `app_with_carthage_dependencies` fixture to use the options? I am not 100% sure they would all be supported for free in the tuist integration

2023-03-18 14:06 UTC, danyf90 commented on Sources/TuistGraph/Models/Dependencies/CarthageDependencies.swift
> +    public enum Options: String {
2 things:
- you are missing the corresponding `Options` in the `ProjectDescription` target
- you should use an enum, similar to what we are doing for `Project.Options`

2023-03-20 09:55 UTC, danyf90 commented on Sources/TuistGraph/Models/Dependencies/CarthageDependencies.swift
> +    public enum Options: String {
Instead of an enum with cases and then take a set of it, it should be a struct, and the cases would become boolean property of the struct

2023-04-04 16:47 UTC, danyf90 commented
Can you update the `app_with_carthage_dependencies` to showcase this?

2023-04-14 11:41 UTC, danyf90 commented on Sources/ProjectDescription/Dependencies/CarthageDependencies.swift
> +    public init(_ dependencies: [Dependency], _ options: Options = .init()) {
let's keep the options mail
```suggestion
    public init(_ dependencies: [Dependency], options: Options = .init()) {
```

2023-04-14 11:43 UTC, danyf90 commented on Sources/TuistDependencies/Carthage/Utils/CarthageController+CarthageArguments.swift
> +    enum CarthageArguments: String, CaseIterable {
If it's used just below, I would just use plain strings there

2023-04-14 11:44 UTC, danyf90 commented on .gitignore
> +
Why is this needed?

2023-04-14 11:44 UTC, danyf90 commented on Sources/TuistGraph/Models/Dependencies/CarthageDependencies.swift
> +        _ options: Options = .init()
```suggestion
        options: Options = .init()
```

2023-04-14 11:44 UTC, danyf90 commented on Sources/TuistGraph/Models/Dependencies/CarthageDependencies.swift
> +        public init(noUseBinaries: Bool = true, useNetRC: Bool = true, cacheBuilds: Bool = true, newResolver: Bool = true) {
Remove the defaults from here as it's not public API

2023-04-25 07:14 UTC, danyf90 commented
@didix21 is this still needed? If yes, could you please address the PR comments? 🙏

2023-04-25 09:33 UTC, didix21 commented
For now, I'll close the PR as I don't have much time for developing it.

2023-04-25 09:33 UTC, closed without merging