Added custom shellPath to ExecuteAction
tuist/tuist pull request #5154
Opened 2023-04-16 09:40 UTC by JCSooHwanCho

### Short description 📝

#3384 introduced custom shellPath to TargetAction. Although ExecutionAction has this feature too, It is missing. So this time, I wanna add this feature.

### Contributor checklist ✅

- [x] The code has been linted using run `./fourier lint tuist --fix`
- [x] The change is tested via unit testing or acceptance testing, or both
- [ ] The title of the PR is formulated in a way that is usable as a changelog entry
- [ ] In case the PR introduces changes that affect users, the documentation has been updated

### Reviewer checklist ✅

- [ ] The code architecture and patterns are consistent with the rest of the codebase
- [ ] Reviewer has checked that, if needed, the PR includes the label `changelog:added`, `changelog:fixed`, or `changelog:changed`, and the title is usable as a changelog entry

2023-04-16 17:48 UTC, danyf90 requested changes

2023-04-16 17:48 UTC, danyf90 commented on CHANGELOG.md
> +
No need to touch the changelog, it's generated from the PR title

2023-04-16 17:48 UTC, danyf90 commented on Sources/ProjectDescription/ExecuteAction.swift
> +    /// if it is nil, "/bin/sh" will be used
If it is nil it uses the Xcode default, the fact that the default is `/bin/sh` shouldn't belongs here.
Also, it fits on one line.

Same for the similar change in TuistGraph

2023-04-17 07:05 UTC, kwridan approved these changes
Thanks @JCSooHwanCho 

Only suggestion I would make is modifying at least one of the actions in the [`ios_with_custom_scheme` fixture](https://github.com/tuist/tuist/tree/main/projects/tuist/fixtures/ios_app_with_custom_scheme) to help demo / showcase this new feature 🙂

Thanks!

2023-04-17 09:16 UTC, danyf90 approved these changes

2023-04-17 11:39 UTC, JCSooHwanCho commented
@kwridan Thank you! I applied.

2023-04-18 10:16 UTC, danyf90 commented
@allcontributors add @JCSooHwanCho  for code

2023-04-20 06:48 UTC, JCSooHwanCho commented
@danyf90 Is there any problem in unit test process? It seems like no test failure, but the process failed with error code. can I get any clue about it?

2023-04-20 07:46 UTC, danyf90 commented
> @danyf90 Is there any problem in unit test process? It seems like no test failure, but the process failed with error code. can I get any clue about it?

This one is failing:     ✖ testXcodeProjStructureDoesNotChangeAfterRegeneration, XCTAssertEqual failed: ("9") is not equal to ("0")

Looks like an issue caused by the bump in XcodeProj 🤔 

@kwridan do you have any experience with it?

2023-04-22 14:22 UTC, JCSooHwanCho commented
@danyf90 @kwridan It turns out that this test fail is result from [this change](https://github.com/tuist/XcodeProj/pull/739)

```
final public class XcodeProj : Equatable {
   // ...
    public var userData: [XcodeProj.XCUserData] <- fail point
   // ... 
}

final public class XCUserData : Equatable, XcodeProj.Writable {
    // ...
    public var schemeManagement: XcodeProj.XCSchemeManagement?  <- fail point
    // ...
}

public struct XCSchemeManagement : Codable, Equatable, XcodeProj.Writable {
   public var schemeUserState: [XcodeProj.XCSchemeManagement.UserStateScheme]? <- fail point
}
```

schemeUserState order is random and equality check is failing

2023-04-22 15:25 UTC, JCSooHwanCho commented
https://opensource.apple.com/source/CommonCrypto/CommonCrypto-60027/CommonCrypto.xcodeproj/xcuserdata/stripes.xcuserdatad/xcschemes/xcschememanagement.plist.auto.html

according to this sample data, It seems that schemeUserState should be dictionary.

2023-04-22 16:35 UTC, kwridan commented
Thanks for investigating this @JCSooHwanCho 🙏

Ouch looks like reads are unstable due to the Dictionary > Array conversion, looks like we missed this when the feature was first introduced even though stability tests were added 😅

https://github.com/tuist/XcodeProj/pull/565/files#diff-55065e34288606fdfc846acb7583090de95cd05838908667a842847f9cd33693R7

Will take a look to see if we can do a sort internally to address this.


> https://opensource.apple.com/source/CommonCrypto/CommonCrypto-60027/CommonCrypto.xcodeproj/xcuserdata/stripes.xcuserdatad/xcschemes/xcschememanagement.plist.auto.html
> 
> according to this sample data, It seems that schemeUserState should be dictionary.

Indeed it appears there's a discrepancy, I wonder if the intention was to preserve the order of the items as they appeared in the plist - but the fact there is an instability leads me to believe that is not the case

2023-04-22 17:08 UTC, kwridan commented
Posted https://github.com/tuist/XcodeProj/pull/758

2023-04-25 07:10 UTC, danyf90 commented
@JCSooHwanCho could you please try using `XcodeProj 8.10.0`? 🙏

2023-04-25 07:47 UTC, JCSooHwanCho commented
@danyf90 Done!

2023-04-26 02:17 UTC, JCSooHwanCho commented
@danyf90 Another faiiure appeared. have you ever experienced with it? It's from plugin acceptance test.

2023-04-28 21:32 UTC, merged