Mark bundle product type doesn't support sources for all platforms
tuist/tuist pull request #5229
Opened 2023-06-12 12:19 UTC by serejahh

### Short description 📝

I've got a warning: `Warning: The target FMPFeedbackForm_FMPFeedbackForm doesn't contain source files.`
This is because we use https://github.com/MacPaw/FMPFeedbackForm. There's a bundle target inside:
<img width="790" alt="image" src="https://github.com/tuist/tuist/assets/2575555/cec71e95-405a-4ccf-aecf-b1a22f74dcfd">
I found that tuist handles iOS and tvOS bundles but doesn't handle other platforms for some reason. So I changed to `a bundle target on ANY platform cannot support sources`

### How to test the changes locally 🧐

> Include a set of steps for the reviewer to test the changes locally (see [the documentation](https://docs.tuist.io/contributors/testing-strategy) for reference).

### Contributor checklist ✅

- [ ] The code has been linted using run `./fourier lint tuist --fix`
- [ ] The change is tested via unit testing or acceptance testing, or both
- [ ] The title of the PR is formulated in a way that is usable as a changelog entry
- [ ] In case the PR introduces changes that affect users, the documentation has been updated

### Reviewer checklist ✅

- [x] The code architecture and patterns are consistent with the rest of the codebase
- [x] Reviewer has checked that, if needed, the PR includes the label `changelog:added`, `changelog:fixed`, or `changelog:changed`, and the title is usable as a changelog entry

2023-06-12 13:06 UTC, serejahh commented
It's a macOS target. I've added a sample project to the branch. Please have a look 🙏
<img width="962" alt="image" src="https://github.com/tuist/tuist/assets/2575555/02095d18-c9a6-4857-b4f6-f49726fda99a">

2023-06-12 15:53 UTC, danyf90 requested changes

2023-06-12 16:23 UTC, serejahh commented on projects/tuist/fixtures/macos_app_with_macOS_bundle_target/Project.swift
> +import ProjectDescription
Sure, I'll remove the project. It's just a showcase how I get the warning

2023-06-13 05:19 UTC, serejahh commented on Sources/TuistGraph/Models/Target.swift
>              return false
Updated `TargetLinter`

2023-06-13 10:25 UTC, danyf90 approved these changes

2023-06-13 10:25 UTC, danyf90 commented on Sources/TuistGenerator/Linter/TargetLinter.swift
> +        }
nit: This could be a guard at the beginning of the method

2023-06-15 07:09 UTC, kwridan approved these changes
Thanks @serejahh 

May be worth extending `TargetLinterTests` for this case.

2023-06-15 11:10 UTC, serejahh commented
Added a test that macOS bundle with no sources doesn't report a warning

2023-06-16 10:58 UTC, merged