Fix cache issues when the graph contains transitive static libraries and frameworks
tuist/tuist pull request #5412
Opened 2023-09-12 12:54 UTC by pepicrft

### Short description 📝
@mstfy reported that when a target has transitive static dependencies, for example, a static library or framework, the generated project with pre-compiled binaries from the cache causes compilation issues. To reproduce it, you can use [this project](https://github.com/tuist/tuist/files/12586529/regression.zip) and run the following sequence of commands:

1. Fetch the dependencies `tuist fetch`.
2. Warm the cache `tuist warm`.
3. Generate the project with the focus on RegressionUI `tuist generate RegressionUI`
4. In the generated project `RegressionUI` doesn't compile because linked dependencies are missing. 

It turns out that the `Target`'s `canLinkStaticProducts` returns `false` for static libraries and frameworks and that leads to those dependencies being excluded. If I understood the logic right, I think the list missed those two types, but I'm not 100% sure about any cascading consequences it might have.

### How to test the changes locally 🧐
Run the same above commands with the changes in this PR.

### Contributor checklist ✅

- [x] The code has been linted using run `./fourier lint tuist --fix`
- [ ] The change is tested via unit testing or acceptance testing, or both
- [x] The title of the PR is formulated in a way that is usable as a changelog entry
- [ ] In case the PR introduces changes that affect users, the documentation has been updated

### Reviewer checklist ✅

- [ ] The code architecture and patterns are consistent with the rest of the codebase
- [ ] Reviewer has checked that, if needed, the PR includes the label `changelog:added`, `changelog:fixed`, or `changelog:changed`, and the title is usable as a changelog entry

2023-09-12 14:17 UTC, kwridan requested changes
Thanks @pepicrft 

I think the issue is scoped to xcframeworks specifically rather than globally all static targets.

I believe the issue we're seeing is a result of the changes made in 

- https://github.com/tuist/tuist/pull/5107
- https://github.com/tuist/tuist/pull/5157

Examining the fixture we can see the following:

✅ `tuist generate` all targets build successfully 
❌ `tuist generate RegressionUI` fails due to being unable to locate `RegressionKit`

I think the cache logic is possibly missing adding an `xcframework` dependencies to `RegressionUI` ? 

The changes in the PR made it such that, if a static target has an `xcframework` dependency it would get a special build phase to get Xcode to process the xcframework without specifically putting in the link build phase (due to some of the other issues that resulted in).

For example `RegressionKit` has:

![Screenshot 2023-09-12 at 15 10 05](https://github.com/tuist/tuist/assets/11914919/515c1031-1316-4428-9430-d3c60355e4ff)

I'd expect `RegressionUI` in the `tuist generate RegressionUI` version of the project to contain at least `RegressionKit.xcframework` (and possibly the transitive `Adjust.xcframework`)

2023-09-15 08:02 UTC, kwridan reviewed
Thanks @pepicrft indeed seems this was the missing piece to traverse precompiled dependencies!

2023-09-18 10:17 UTC, pepicrft commented on projects/tuist/fixtures/app_with_spm_dependencies/StringifyMacro/Package.swift
> +// swift-tools-version: 5.8
This was causing acceptance tests to fail because we don't use the new Xcode version on CI (yet)

2023-09-18 15:26 UTC, kwridan reviewed
Thanks @pepicrft

2023-09-18 15:26 UTC, kwridan commented on Sources/TuistCore/Graph/GraphTraverser.swift
> +        })
I believe we'll need to obtain all the transitive unlinked xcframeworks as opposed to all, for example:

![example](https://github.com/tuist/tuist/assets/11914919/aba5c2cf-abc3-4d7e-ae11-92e43dbee69d)

This method would only need return xcframeworks `A` and `B`, it shouldn't need `C`

```suggestion
        }, skip: canDependencyLinkStaticProducts)
```

2023-09-18 15:26 UTC, kwridan commented on Tests/TuistCoreTests/Graph/GraphTraverserTests.swift
> +    }
this is really helpful 👍 

we can augment it with the example above

2023-09-19 12:13 UTC, kwridan approved these changes
Thanks @pepicrft

2023-09-19 12:21 UTC, merged