Migrate lint and format to Makefile
tuist/tuist pull request #5440
Opened 2023-09-25 06:14 UTC by kwridan

### Short description 📝

- To ease contributions to those that don't have a ruby setup, the SwiftLint and Swiftformat shell calls have been migrated to the Makefile
- The SwiftFormat config was updated to exclude one of the fixtures that is added as a submodule
- The github token was moved to the github step to avoid requiring it for all makefile incovations

### How to test the changes locally 🧐

- Run `make tuist_lint`
- Verify SwiftLint and SwiftFormat are run
- Verify no prompt to login to GitHub is required

### Contributor checklist ✅

- [ ] The code has been linted using run `./fourier lint tuist --fix`
- [ ] The change is tested via unit testing or acceptance testing, or both
- [ ] The title of the PR is formulated in a way that is usable as a changelog entry
- [ ] In case the PR introduces changes that affect users, the documentation has been updated

### Reviewer checklist ✅

- [ ] The code architecture and patterns are consistent with the rest of the codebase
- [ ] Reviewer has checked that, if needed, the PR includes the label `changelog:added`, `changelog:fixed`, or `changelog:changed`, and the title is usable as a changelog entry

2023-09-25 07:31 UTC, danyf90 approved these changes

2023-09-25 08:42 UTC, danyf90 approved these changes

2023-09-25 08:43 UTC, danyf90 requested changes
Shouldn't we also replace it in `tuist/tuist/.github/workflows/tuist.yml`?
How hard would it be to get rid of the other fourier lint commands as well?

2023-09-25 09:17 UTC, kwridan commented
> Shouldn't we also replace it in tuist/tuist/.github/workflows/tuist.yml

Good point would need to have 2 separate actions `lint` `lint-fix` or something like that one that works in lint mode one that applies fixes.

> How hard would it be to get rid of the other fourier lint commands as well?

Fourier lint also lints ruby code - hence why originally I made it `tuist_lint` 😅 - not too sure on what's needed for the ruby side of things so kept that as is.

2023-09-25 10:06 UTC, danyf90 approved these changes

2023-09-28 11:29 UTC, pepicrft commented on Makefile
> +lint-fix:
@kwridan I'll merge [this one](https://github.com/tuist/tuist/pull/5451) first and then push a commit to this one extracting the logic into their own scripts.

2023-09-28 13:36 UTC, danyf90 approved these changes

2023-09-28 13:36 UTC, danyf90 commented on Makefile
> +	./make/tasks/lint.sh
I would make `lint.sh` take a --fix parameter and handle the change there

Not sure if it's also possible to define arguments for make (I guess not)

2023-09-29 06:25 UTC, merged