Fix linking of precompiled static xcframeworks that are transitive dependencies of a static framework
tuist/tuist pull request #5459
Opened 2023-09-29 14:29 UTC by pepicrft

Related https://github.com/tuist/tuist/pull/5412

### Short description 📝

[This PR](https://github.com/tuist/tuist/pull/5412) only solved the issue partially. When in a dependency graph we have a static framework with a static precompiled xcframework as a transitive dependency, the generated project was missing a build phase to resolve the transitive module at compile-time. The linked PR addressed it for targets that are xcframeworks, but we should have included the other scenarios.

### How to test the changes locally 🧐

Get the project [mentioned in this issue](https://github.com/tuist/tuist/pull/5412) and run the described steps there.

### Contributor checklist ✅

- [x] The code has been linted using run `make lint-fix`
- [x] The change is tested via unit testing or acceptance testing, or both
- [x] The title of the PR is formulated in a way that is usable as a changelog entry
- [ ] In case the PR introduces changes that affect users, the documentation has been updated

### Reviewer checklist ✅

- [ ] The code architecture and patterns are consistent with the rest of the codebase
- [ ] Reviewer has checked that, if needed, the PR includes the label `changelog:added`, `changelog:fixed`, or `changelog:changed`, and the title is usable as a changelog entry

2023-09-29 14:59 UTC, shahzadmajeed approved these changes

2023-09-29 14:59 UTC, shahzadmajeed commented on Sources/TuistGraph/Graph/GraphDependency.swift
> +        case let .library(_, _, linking, _, _): return linking == .static
Super Nit: Could these can be combined to return a true for readability?

```swift
case let .xcframework(_, _, _, linking, _),
  let .framework(_, _, _, _, linking, _, _),
  let .library(_, _, linking, _, _) where linking == .static:
  return true
```

2023-09-29 15:39 UTC, waltflanagan approved these changes

2023-09-29 18:37 UTC, danyf90 approved these changes

2023-09-30 15:17 UTC, kwridan requested changes
Thanks @pepicrft did the previous PR not address the issue? From my testing there it seemed though it did. 

Is there a new fixture scenario which requires these changes? Would be helpful to draw out a graph of this to help visualise the scenario that needs addressing. 

Thanks

2023-09-30 15:17 UTC, kwridan commented on Tests/TuistCoreTests/Graph/GraphTraverserTests.swift
> +            .xcframework(
I don't believe this is quite right 🤔 the assertion was correct before the changes. 

See https://github.com/tuist/tuist/pull/5412#discussion_r1328900851 for the original

2023-09-30 15:17 UTC, kwridan commented on Sources/TuistCore/Graph/GraphTraverser.swift
> +            skip: { $0.isDynamicPrecompiled }
In this method we're trying to collect all xcframeworks transitively 

XCFrameworkA -> XCFrameworkB -> ...

The skip clause determines when to terminate the traversal of a specific graph path, an xcframework can be dynamic and is precompiled as such in some cases the traversal here will terminate earlier than we want it to (e.g. if XCFrameworkB is dynamic) 

In this method the goal is to skip non xcframeworks so it was correct before. 

A change may be needed if the following can ever be possible (somehow via Tuist cache logic, but it's not possible via public API). 

XCFrameworkA -> dynamicLibA.dylib -> XCFrameworkB 

XCFrameworkA -> PrecompiledFrameworkA.framework -> XCFrameworkB 

In which case the skip clause would be revised to not skip precompiled libraries and frameworks - but this need a bit more testing to verify.

2023-09-30 16:41 UTC, pepicrft commented
> Thanks @pepicrft did the previous PR not address the issue? From my testing there it seemed though it did.
> 
> Is there a new fixture scenario which requires these changes? Would be helpful to draw out a graph of this to help visualise the scenario that needs addressing.
> 
> Thanks

There are two scenarios:
1. The precompiled static `.xcframework` is a transitive dependency with all the precompiled nodes in the branch being `.xcframeworks`.
2. The precompiled static `.xcframework` is a transitive dependency with some precompiled nodes in the graph being `.frameworks`.

The initial fix only addressed 1, but 2 led to compilation issues. 

![image](https://github.com/tuist/tuist/assets/663605/dd16f02b-1fe1-4a54-bde4-b8e24ac06f48)

> The skip clause determines when to terminate the traversal of a specific graph path, an xcframework can be dynamic and is precompiled as such in some cases the traversal here will terminate earlier than we want it to (e.g. if XCFrameworkB is dynamic)

Isn't that what we want? If `XCFrameworkB` is dynamic, the module interfaces beyond that point are only relevant from `XCFrameworkB`, where the linking is happening. I might be missing something.

> XCFrameworkA -> PrecompiledFrameworkA.framework -> XCFrameworkB

This is representative of the graph that we are working with. As you pointed out, this is not possible via the public API, but it's a graph scenario that users find when using the cache. I think `staticPrecompiledXCFrameworksDependencies` is misleading, so I'd suggest that we rename the function and add some acceptance tests to make sure Xcode compiles each of those scenarios.

2023-10-02 07:00 UTC, kwridan commented
Thanks for the clarification @pepicrft 

The missing case is indeed transitive XCFrameworks via other precompiled `.framework`s for this the skip clause would need to be revised to also skip non precompiled dependencies (e.g. `.target`, `.sdk` etc...) - for example 

![example](https://github.com/tuist/tuist/assets/11914919/331cc66d-2da6-4a5c-8f88-82d35163de34)

`Static Framework A` shouldn't include any of the `Static Framework B` target transitive dependencies in this setup

2023-10-02 07:34 UTC, pepicrft commented
> The missing case is indeed transitive XCFrameworks via other precompiled .frameworks for this the skip clause would need to be revised to also skip non precompiled dependencies (e.g. .target, .sdk etc...) - for example

Good catch! By the way, which tool do you use for drawing those dependency graphs?

I adjusted the `skip` as suggested and extended the test scenario to account for it.

2023-10-03 06:53 UTC, kwridan approved these changes
Thanks for the updates @pepicrft - changes look good 👍 

> By the way, which tool do you use for drawing those dependency graphs?

been using draw.io, their export in dark mode seems a bit broken so been taking screenshots from the online editor 🙈

2023-10-03 07:42 UTC, merged